<h1>Categorias</h1>
<br>
<a href="<?php echo $this->url('livraria-admin', ['controller'=>'categorias', 'action'=>'new']); ?>" class="btn btn-default">Nova Categoria</a>
<br>
<br>
<table class="table">
    <tr>
        <th>
            Id
        </th>
        <th>
            Nome
        </th>
        <th>
            Ação
        </th>
    </tr>
    <?php foreach($this->data as $entity): ?>
    <tr>
        <td>
            <?php echo $entity->getId(); ?>
        </td>
        <td>
            <?php echo $entity->getNome(); ?>
        </td>
        <td>
            <a href="<?php echo $this->url('livraria-admin-interna', ['controller'=>'categorias','action'=>'edit','id'=>$entity->getId()]); ?>">Editar</a>
            <a href="<?php echo $this->url('livraria-admin-interna', ['controller'=>'categorias','action'=>'delete','id'=>$entity->getId()]); ?>">Apagar</a>
        </td>
    </tr>
    <?php endforeach;?>
</table>

<br>

<?php echo $this->paginationControl($this->data, 'Sliding', 'paginator'); ?>